version = 1
SPDX-PackageName = "cluster-api-provider-ironcore-metal"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/cluster-api-provider-ironcore-metal"

[[annotations]]
path = [".github/**", ".gitignore", ".dockerignore", ".golangci.yml", "CODEOWNERS", "Dockerfile", "Makefile", "PROJECT", "config/**", "go.mod", "go.sum", "hack/**", "scripts/**", "Tiltfile", "tilt-provider.json", "templates/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/**", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
